Repository kensho-technologies/graphql-compiler, pull requests merged in 2019-12, with the labels that each got.

#683 Remove Python 2 support
  .travis.yml
  CONTRIBUTING.rst
  Pipfile.lock
  Pipfile.py2.lock
  docs/source/about/contributing.rst
  scripts/make_pipenv_lockfiles.sh
  scripts/make_py2_venv.sh
  scripts/use_appropriate_lockfile.sh
  setup.py
Labels: maintainer quality-of-life

#689 Add mypy dependency and linter check.
  Pipfile
  Pipfile.lock
  graphql_compiler/schema_generation/sqlalchemy/scalar_type_mapper.py
  scripts/lint.sh
  setup.cfg
Labels: maintainer quality-of-life

#691 Add type hints to test_helpers.py.
  graphql_compiler/schema/__init__.py
  graphql_compiler/schema/typedefs.py
  graphql_compiler/tests/test_helpers.py
Labels: maintainer quality-of-life

#694 Only start dockerized databases for tests, not for lint.
  .travis.yml
Labels: maintainer quality-of-life

#693 Add type hints to the compiler's test input data file.
  graphql_compiler/tests/test_input_data.py
Labels: maintainer quality-of-life

#695 Build pushes to master branch and new version tags.
  .travis.yml
Labels: maintainer quality-of-life

#697 Upgrade to newer major linter and test framework versions.
  Pipfile
  Pipfile.lock
  graphql_compiler/compiler/blocks.py
  graphql_compiler/schema_generation/sqlalchemy/__init__.py
Labels: maintainer quality-of-life

#699 Fix a couple of type errors and add more types.
  graphql_compiler/tests/integration_tests/test_backends_integration.py
Labels: maintainer quality-of-life

#700 Even more type hints on more test code.
  graphql_compiler/tests/snapshot_tests/test_cost_estimation.py
  graphql_compiler/tests/snapshot_tests/test_orientdb_match_query.py
  graphql_compiler/tests/snapshot_tests/test_query_pagination.py
  graphql_compiler/tests/test_data_tools/neo4j_graph.py
  graphql_compiler/tests/test_data_tools/orientdb_graph.py
  graphql_compiler/tests/test_data_tools/redisgraph_graph.py
  graphql_compiler/tests/test_data_tools/schema.py
Labels: maintainer quality-of-life

#701 Add type hints to more low-hanging-fruit test files.
  graphql_compiler/tests/test_emit_output.py
  graphql_compiler/tests/test_end_to_end.py
  graphql_compiler/tests/test_ir_generation_errors.py
  graphql_compiler/tests/test_location.py
  graphql_compiler/tests/test_safe_match_and_gremlin.py
  graphql_compiler/tests/test_test_data.py
Labels: maintainer quality-of-life

#696 Improve API consistency between SQL and other compilation targets
  README.rst
  docs/source/index.rst
  docs/source/supported_databases/neo4j_and_redisgraph.rst
  graphql_compiler/__init__.py
  graphql_compiler/compiler/common.py
  graphql_compiler/tests/integration_tests/integration_test_helpers.py
  graphql_compiler/tests/integration_tests/test_backends_integration.py
  graphql_compiler/tests/snapshot_tests/test_orientdb_match_query.py
  graphql_compiler/tests/test_compiler.py
  graphql_compiler/tests/test_end_to_end.py
Labels: documentation, user friendliness

#705 Remove frozendict package dependency.
  Pipfile
  Pipfile.lock
  graphql_compiler/cost_estimation/statistics.py
  graphql_compiler/tests/schema_generation_tests/test_orientdb_schema_generation.py
  setup.py
Labels: maintainer quality-of-life, user friendliness

#703 Switch to Python 3.8 for lint and local development.
  .travis.yml
  CONTRIBUTING.rst
  Pipfile
  Pipfile.lock
  docs/source/about/contributing.rst
  graphql_compiler/compiler/helpers.py
  graphql_compiler/tests/schema_generation_tests/test_sqlalchemy_schema_generation.py
Labels: maintainer quality-of-life

#707 Annotate more test files with type hints.
  graphql_compiler/tests/test_explain_info.py
  graphql_compiler/tests/test_graphql_pretty_print.py
  graphql_compiler/tests/test_macro_expansion.py
  graphql_compiler/tests/test_macro_expansion_errors.py
  graphql_compiler/tests/test_macro_schema.py
  graphql_compiler/tests/test_macro_validation.py
Labels: maintainer quality-of-life

#710 Add type hints to a few files in the compiler submodule.
  graphql_compiler/compiler/blocks.py
  graphql_compiler/compiler/compiler_entities.py
  graphql_compiler/compiler/expressions.py
  graphql_compiler/compiler/helpers.py
  graphql_compiler/compiler/ir_lowering_match/utils.py
  graphql_compiler/tests/test_emit_output.py
  graphql_compiler/tests/test_location.py
Labels: documentation, maintainer quality-of-life
