Repository kensho-technologies/graphql-compiler, pull requests merged in 2020-10, with the labels that each got.

#939 Add InterpreterAdapter class with thorough class docstring.
  graphql_compiler/interpreter/typedefs.py
Labels: documentation, enhancement

#706 Use GitHub Actions instead of Travis CI for testing and linting
  .github/workflows/tests_and_lint.yml
  .travis.yml
  README.rst
  scripts/install_ubuntu_ci_core_dependencies.sh
  scripts/lint.sh
Labels: maintainer quality-of-life

#943 Add Python 3.9 to our testing matrix.
  .github/workflows/tests_and_lint.yml
  setup.py
Labels: enhancement

#944 Add docstring for get_tokens_of_type().
  graphql_compiler/interpreter/typedefs.py
Labels: documentation

#950 docs: update code of conduct to v2.0
  CODE_OF_CONDUCT.rst
Labels: documentation

#949 Add docstring for can_coerce_to_type().
  graphql_compiler/interpreter/typedefs.py
Labels: documentation

#947 Add docstring for project_property().
  graphql_compiler/interpreter/typedefs.py
Labels: documentation

#945 Add debug and test helpers for interpreters.
  graphql_compiler/interpreter/debugging.py
Labels: documentation, enhancement

#956 Indent examples in docstring, for consistency.
  graphql_compiler/interpreter/typedefs.py
Labels: documentation
